ALTER TABLE employee
ADD COLUMN IF NOT EXISTS record_status VARCHAR(10) DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS stamp VARCHAR(60);

ALTER TABLE jobhistory
ADD COLUMN IF NOT EXISTS record_status VARCHAR(10) DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS stamp VARCHAR(60);

ALTER TABLE job
ADD COLUMN IF NOT EXISTS record_status VARCHAR(10) DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS stamp VARCHAR(60);

ALTER TABLE department
ADD COLUMN IF NOT EXISTS record_status VARCHAR(10) DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS stamp VARCHAR(60);